/**
 * Bangun public/sw.js setelah `next build`.
 *
 * Strategi offline (PWA scope §8):
 *  - Precache: semua aset statis hashed dari .next/static (JS/CSS/font),
 *    worker pdf.js, ikon, manifest, dan dokumen HTML semua route tool.
 *  - Dokumen (navigasi) & RSC payload: network-first → fallback cache
 *    (kunjungan online pertama menyimpan salinan untuk offline).
 *  - Aset statis: cache-first (hashed = immutable).
 *
 * `next build && node scripts/gen-sw.js`
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const STATIC_DIR = path.join(ROOT, ".next", "static");
const OUT = path.join(ROOT, "public", "sw.js");
const VERSION = String(Date.now());

const ROUTES = [
  "/",
  "/tools/read",
  "/tools/merge",
  "/tools/split",
  "/tools/rotate",
  "/tools/organize",
  "/tools/extract",
  "/tools/pdf-to-jpg",
  "/tools/jpg-to-pdf",
  "/tools/page-numbers",
  "/tools/watermark",
  "/tools/logo-header",
  "/tools/remove-background",
  "/tools/compress",
  "/tools/protect",
  "/tools/unlock",
  "/tools/ocr",
  "/tools/office-to-pdf",
];

/** Kumpulkan semua file .next/static → URL /_next/static/... */
function collectStaticUrls(dir, urls = []) {
  if (!fs.existsSync(dir)) return urls;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      collectStaticUrls(p, urls);
    } else {
      urls.push("/_next/static/" + path.relative(STATIC_DIR, p).split("\\").join("/"));
    }
  }
  return urls;
}

const precache = [
  ...collectStaticUrls(STATIC_DIR),
  "/pdf.worker.min.mjs",
  "/manifest.webmanifest",
  "/icon.svg",
  "/icons/icon-192.png",
  "/icons/icon-512.png",
  ...ROUTES,
];

const sw = `/* GENERATED by scripts/gen-sw.js — jangan edit manual. V${VERSION} */
const CACHE_STATIC = "pdfconverter-static-v1";
const CACHE_PAGES = "pdfconverter-pages-v1";
const CACHE_RSC = "pdfconverter-rsc-v1";
const PRECACHE = ${JSON.stringify(precache)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(CACHE_STATIC)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((k) => !k.startsWith("pdfconverter-"))
            .map((k) => caches.delete(k))
        )
      )
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // RSC payload (navigasi client-side Next.js)
  if (req.headers.get("RSC") === "1") {
    event.respondWith(networkFirst(req, CACHE_RSC));
    return;
  }

  // Dokumen (navigasi penuh) — network-first
  if (req.destination === "document") {
    event.respondWith(networkFirst(req, CACHE_PAGES));
    return;
  }

  // Aset statis (hashed, immutable) — cache-first
  event.respondWith(cacheFirst(req));
});

async function networkFirst(req, cacheName) {
  const cache = await caches.open(cacheName);
  try {
    const res = await fetch(req);
    if (res.ok) cache.put(req, res.clone());
    return res;
  } catch {
    const hit = await cache.match(req);
    if (hit) return hit;
    // Fallback terakhir: halaman utama dari precache
    if (req.destination === "document") {
      const home = await caches.match("/");
      if (home) return home;
    }
    return new Response("Offline", { status: 503 });
  }
}

async function cacheFirst(req) {
  const hit = await caches.match(req);
  if (hit) return hit;
  const res = await fetch(req);
  if (res.ok) {
    const cache = await caches.open(CACHE_STATIC);
    cache.put(req, res.clone());
  }
  return res;
}
`;

fs.writeFileSync(OUT, sw);
console.log(`sw.js dibuat: ${precache.length} URL diprecache (V${VERSION})`);
